### PR TITLE
Add search_replace.py

### PR DESCRIPTION
**Pull request by jflory7**
# Summary

The original use case for this script was when the Minecraft server changed worlds. This meant introducing multiple worlds with strings like `world` and now `world_new` into thousands of player data files. This script solves this problem by searching and replacing all the strings to make them consistent.

# Caveat

This will take many text files at once and replace the needed string without having to run it individually on every file. The only shortcoming of this script is that there are multiple strings which will need to be replaced, which means a lot of backup files will be created. There's probably a more elegant way of taking multiple strings and replacing them at once, instead of having to re-run the script multiple times.

# Open for feedback

This script will be ran against a few thousand YAML files. All peer review and feedback is welcome, and very much appreciated.

### CODE REVIEW

**Comment by jflory7** [comment]
@nathaniel486 If you have some time, your eyes would be appreciated here!

**Comment by Serubin** [comment]
That looks really clean to me. I would personally consider moving the .bak files to a bak/ directory - but that's not of importance.

**Comment by jflory7** [comment]
@Serubin Thanks! And yeah, that would make things a little easier to deal with. @nathaniel486 volunteered to jump on making that change, so he's going to get some git practice and try adding that into this PR.

**Comment by Serubin** [comment]
Out of curiosity - someone in your email change mentioned that you basically rewrote sed in python. Why not just use sed or perl?

**Comment by Chris-Bitler** [comment]
Looks pretty clean to me in my very little knowledge of python 👍

**Comment by jflory7** [comment]
@Serubin Yeah, fair questions. Two reasons that aren't very valid answers: (1) I was wanting to dabble with Python and (2) I didn't know think using `sed` until after I wrote the code. 😆 

@Chris-Bitler Great, thanks!

**Pull request merged**
